
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-chart-deployment
  labels:
    app: bmi-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bmi-app
  template:
    metadata:
      labels:
        app: bmi-app
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.path | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: bmi-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
