
apiVersion: v1
kind: Service
metadata:
  name: bmi-app-svc
  labels:
    app: bmi-app
spec:
  selector:
    app: bmi-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
